# netlify.toml
[build]
  command = "npm run build"
  functions = "functions"
  publish = "public"
  command = "python generate_tokens.py"
  command = "python main.py"
  publish = "public/" 
  functions = "functions"
